#!/bin/sh

# sudopass = abcd
# xp-username = pihizi
# xp-password = abcd
# xp-url = \\192.168.56.101\projects
myini=$(pwd)"/.bin/add.ini"

if [ $# -lt 1 ]
then
    echo "请输入您要mount的目标"
    echo $(sed -n 's/\(.*\)-username *= *[^ ]*.*/\1/p' < $myini)
    exit 1
fi

check_empty() {
    if [ -z "$1" ] 
    then
        exit 1
    fi
}

SudoPassWord=$(sed -n 's/.*sudopass *= *\([^ ]*.*\)/\1/p' < $myini)
check_empty $SudoPassWord
tmpusername=$(sed -n 's/.*'$1'-username *= *\([^ ]*.*\)/\1/p' < $myini)
check_empty $tmpusername
tmppassword=$(sed -n 's/.*'$1'-password *= *\([^ ]*.*\)/\1/p' < $myini)
check_empty $tmppassword
tmpremote=$(sed -n 's/.*'$1'-url *= *\([^ ]*.*\)/\1/p' < $myini)
check_empty $tmpremote

i_mount() {
    tmp="/home/$USER/smb/$4"
    if [ ! -d "$tmp" ]
    then
        mkdir -p "$tmp"
    fi
    echo "$SudoPassWord" | sudo -S mount -t smbfs -o username="$1",password="$2",rw,uid=1000,gid=1000 "$3" "$tmp"
}

i_mount "$tmpusername" "$tmppassword" "$tmpremote" "$1"
